### ISSUE TITLE
Redirection to www.default.asp on IIS 8 on Windows Server 2012 R2

### ISSUE THREAD

**Issue by nhua6456** [danielskowronski/iis-lister#1]
I tried to install the iis-lister to my webserver that is hosted by IIS 8 but it keeps redirecting to www.default.asp

I've checked the HTTP logs and they don't seem very unusual. I believe the ASP file is ok because when I did the fresh install, I was able to see a red screen with some non-english text on it, but after I changed the IP address to the IP address that I want to access from, then it started redirecting me to www.default.asp.

**Comment by danielskowronski** [comment]
I've found what is causing this state - if script is in root directory of webserver it tries to redirect somewhere, if it's in some subdirectory - everything works. I'll investigate.

**Comment by danielskowronski** [comment]
Bug located, thanks!
